<a href="https://colab.research.google.com/github/WahyuBagus8545/DES-Cipher/blob/main/des.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Program kriptografi algoritma DES
by Mohammad Wahyu Bagus Dwi Satya

In [ ]:
import string
import random
import numpy as np

In [ ]:
#plainText = input('Masukkan kata : ')

In [ ]:
condition = True
while condition:
  plainText = input("Masukkan teks (minimal 8 karakter): ")

    # Menggunakan slicing untuk memastikan hanya 8 karakter pertama yang digunakan
  plainText = plainText[:8]

  if len(plainText) >= 8:
        print("Input valid:",  plainText)
        break
  else:
        # Menambahkan karakter acak jika panjang input kurang dari 8
      additional_characters = ''.join(random.choices(string.ascii_letters, k=8 - len( plainText)))
      plainText += additional_characters

  print(f"Panjang input kurang dari 8. Menambahkan karakter acak: { plainText}")
  condition = False


Masukkan teks (minimal 8 karakter): jerangkong
Input valid: jerangko


In [ ]:
#mainKey = input('Masukkan kunci : ')

In [ ]:
condition = True
while condition:
  mainKey = input("Masukkan teks (minimal 8 karakter): ")

    # Menggunakan slicing untuk memastikan hanya 8 karakter pertama yang digunakan
  mainKey = mainKey[:8]

  if len(mainKey) >= 8:
        print("Input valid:",  mainKey)
        break
  else:
        # Menambahkan karakter acak jika panjang input kurang dari 8
      additional_characters = ''.join(random.choices(string.ascii_letters, k=8 - len(mainKey)))
      mainKey += additional_characters

  print(f"Panjang input kurang dari 8. Menambahkan karakter acak: {mainKey}")
  condition = False

Masukkan teks (minimal 8 karakter): kupu
Panjang input kurang dari 8. Menambahkan karakter acak: kupuKoka


# ENKRIPSI

In [ ]:
char_to_hexa = {'a':'61', 'b': '62', 'c': '63', 'd': '64', 'e': '65', 'f': '66', 'g': '67', 'h': '68', 'i':'69',
                'j':'6a', 'k':'6b', 'l':'6c', 'm':'6d', 'n':'6e', 'o':'6f', 'p':'70', 'q':'71', 'r':'72', 's':'73',
                't':'74', 'u':'75', 'v':'76', 'w':'77', 'x':'78', 'y':'79', 'z':'7a'}

hexa_to_bin = {
                '0': '0000', '1': '0001', '2': '0010', '3': '0011', '4': '0100',
                '5': '0101', '6': '0110', '7': '0111', '8': '1000', '9': '1001',
                'a': '1010', 'b': '1011', 'c': '1100', 'd': '1101', 'e': '1110', 'f': '1111'
               }


hexa_to_char = {
                '61':'a', '62': 'b', '63': 'c', '64': 'd', '65': 'e', '66': 'f', '67': 'g', '68': 'h', '69':'i',
                '6a':'j', '6b':'k', '6c':'l', '6d':'m', '6e':'n', '6f':'o', '70':'p', '71':'q', '72':'r', '73':'s',
                '74':'t', '75':'u', '76':'v', '77':'w', '78':'x', '79':'y', '7a':'z', '41':'A', '42':'B', '43':'C',
                '44':'D', '45':'E', '46':'F', '47':'G', '48':'H', '49':'I', '4a':'J', '4b':'K', '4c':'L', '4d':'M', '4e':'N',
                '4f':'O', '50':'P', '51':'Q', '52':'R', '53':'S', '54':'T', '55':'U', '56':'V', '57':'W', '58':'X', '59':'Y', '5a':'Z'
               }

In [ ]:
cleanText=""
for i in plainText:
  if i == ' ':
    continue
    # Perulangan untuk dimana untuk setiap spasi / karakter kosong maka akan dilewati
  else:
    cleanText += i
     # Jika bukan spasi, karakter tersebut ditambahkan ke dalam string cleanText.

# Dengan cara ini, kodingan ini menghasilkan text versi "bersih" dengan menghapus karakter spasi.
print(cleanText)

jerangko


In [ ]:
initialText = cleanText.lower()

if len(initialText) < 8 or len(initialText) > 8:
            print("Please, enter 64 bits or 8 bytes as initial message ")
else:
    byteMsg = initialText.encode('utf-8')
    hexaMsg = str(byteMsg.hex())
    tempMsg = []
    s = ""
    for i in str(hexaMsg):
      for j in hexa_to_bin:
          if i == j:
            tempMsg.append(hexa_to_bin[j])
    binMsg = s.join(tempMsg)
    formatted_binary_msg = ' '.join([binMsg[i:i+8] for i in range(0, len(binMsg), 8)])
    print(formatted_binary_msg, "\n")

01101010 01100101 01110010 01100001 01101110 01100111 01101011 01101111 



In [ ]:
initialKey = mainKey.lower()

if len(initialKey) < 8 or len(initialKey) > 8:
    print("Please, enter 64 bits or 8 bytes as initial key ")
else:
      temphKey = []
      s = ""
      for i in str(initialKey):
        for j in char_to_hexa:
          if i == j:
            temphKey.append(char_to_hexa[j])
      # Join all the elements in temphKey after the loops
      hexaKey = s.join(temphKey)
      print("The hexadecimal representational for your key is:")
      print(hexaKey, "\n")

      tempKey   = []
      s         = ""
      for i in str(hexaKey):
        for j in hexa_to_bin:
                if i == j:
                    tempKey.append(hexa_to_bin[j])
        binKey  = s.join(tempKey)
      print("The binary representational for your key is:")
      print(binKey,"\n")


The hexadecimal representational for your key is:
6b7570756b6f6b61 

The binary representational for your key is:
0110101101110101011100000111010101101011011011110110101101100001 



In [ ]:
len(binKey)

64

Langkah 1 Permutasi awal

In [ ]:
IP = [58, 50, 42, 34, 26, 18, 10, 2,
      60, 52, 44, 36, 28, 20, 12, 4,
      62, 54, 46, 38, 30, 22, 14, 6,
      64, 56, 48, 40, 32, 24, 16, 8,
      57, 49, 41, 33, 25, 17, 9, 1,
      59, 51, 43, 35, 27, 19, 11, 3,
      61, 53, 45, 37, 29, 21, 13, 5,
      63, 55, 47, 39, 31, 23, 15, 7]

matrikIP=[IP[i:i+8] for i in range(0, len(IP), 8)]
for row in matrikIP:
    print(row)

[58, 50, 42, 34, 26, 18, 10, 2]
[60, 52, 44, 36, 28, 20, 12, 4]
[62, 54, 46, 38, 30, 22, 14, 6]
[64, 56, 48, 40, 32, 24, 16, 8]
[57, 49, 41, 33, 25, 17, 9, 1]
[59, 51, 43, 35, 27, 19, 11, 3]
[61, 53, 45, 37, 29, 21, 13, 5]
[63, 55, 47, 39, 31, 23, 15, 7]


In [ ]:
i = 0
s = ""

permuted_text = [binMsg[i - 1] for i in IP]

#print("The message after the IP \n")
msgIP = s.join(permuted_text)
print(msgIP, "\n")

1111111100000100101100101110101000000000111111111101000111110101 



Langkah 2

In [ ]:
# 32 bit
L0 = msgIP[:32]
R0 = msgIP[-32:]

LeftSideList = [L0]
#L0
formatted_binary_L0 = ' '.join([L0[i:i+8] for i in range(0, len(L0), 8)])
print("L0 : "+formatted_binary_L0)

RightSideList = [R0]
#R0
formatted_binary_R0 = ' '.join([R0[i:i+8] for i in range(0, len(R0), 8)])
print("R0 : "+formatted_binary_R0)

L0 : 11111111 00000100 10110010 11101010
R0 : 00000000 11111111 11010001 11110101


Langkah 3 Pembangkitan Kunci

In [ ]:
PC1 = [57,   49,    41,   33,    25,    17,    9,
        1,   58,    50,   42,    34,    26,   18,
       10,    2,    59,   51,    43,    35,   27,
       19,   11,     3,   60,    52,    44,   36,
       63,   55,    47,   39,    31,    23,   15,
        7,   62,    54,   46,    38,    30,   22,
       14,    6,    61,   53,    45,    37,   29,
       21,   13,     5,   28,    20,    12,    4]

matrikPC1 = np.array(PC1[:56]).reshape(8, 7)
print(matrikPC1)

[[57 49 41 33 25 17  9]
 [ 1 58 50 42 34 26 18]
 [10  2 59 51 43 35 27]
 [19 11  3 60 52 44 36]
 [63 55 47 39 31 23 15]
 [ 7 62 54 46 38 30 22]
 [14  6 61 53 45 37 29]
 [21 13  5 28 20 12  4]]


Langkah 4 Permutasi kunci

In [ ]:
i = 0
s = ""

# 56 bit
permuted_key = [binKey[i - 1] for i in PC1]

#print("The message after the IP \n")
keyPC1 = s.join(permuted_key)
print(keyPC1, "\n")

#Langkah 5
# 28 bit
C0 = keyPC1[:28]
D0 = keyPC1[-28:]

LeftSideKey = [C0]
#C0
formatted_binary_C0 = ' '.join([C0[i:i+7] for i in range(0, len(C0), 7)])
print("C0 : "+formatted_binary_C0)

RightSideKey = [D0]
#D0
formatted_binary_D0 = ' '.join([D0[i:i+7] for i in range(0, len(D0), 7)])
print("D0 : "+formatted_binary_D0)

00000000111111111111111100000111000100101010011100011110 

C0 : 0000000 0111111 1111111 1110000
D0 : 0111000 1001010 1001110 0011110


In [ ]:
C1 = C0[1:28] + C0[0]; D1 = D0[1:28] + D0[0]

C2 = C1[1:28] + C1[0]; D2 = D1[1:28] + D1[0]

C3 = C2[2:28] + C2[0] + C2[1]; D3 = D2[2:28] + D2[0] + D2[1]

C4 = C3[2:28] + C3[0] + C3[1]; D4 = D3[2:28] + D3[0] + D3[1]

C5 = C4[2:28] + C4[0] + C4[1]; D5 = D4[2:28] + D4[0] + D4[1]

C6 = C5[2:28] + C5[0] + C5[1]; D6 = D5[2:28] + D5[0] + D5[1]

C7 = C6[2:28] + C6[0] + C6[1]; D7 = D6[2:28] + D6[0] + D6[1]

C8 = C7[2:28] + C7[0] + C7[1]; D8 = D7[2:28] + D7[0] + D7[1]

C9 = C8[1:28] + C8[0]; D9 = D8[1:28] + D8[0]

C10 = C9[2:28] + C9[0] + C9[1]; D10 = D9[2:28] + D9[0] + D9[1]

C11 = C10[2:28] + C10[0] + C10[1]; D11 = D10[2:28] + D10[0] + D10[1]

C12 = C11[2:28] + C11[0] + C11[1]; D12 = D11[2:28] + D11[0] + D11[1]

C13 = C12[2:28] + C12[0] + C12[1]; D13 = D12[2:28] + D12[0] + D12[1]

C14 = C13[2:28] + C13[0] + C13[1]; D14 = D13[2:28] + D13[0] + D13[1]

C15 = C14[2:28] + C14[0] + C14[1]; D15 = D14[2:28] + D14[0] + D14[1]

C16 = C15[1:28] + C15[0]; D16 = D15[1:28] + D15[0]

# Penggabungan Cn dan Dn


Key1  = C1 + D1; Key2  = C2 + D2; Key3  = C3 + D3; Key4  = C4 + D4
Key5  = C5 + D5; Key6  = C6 + D6; Key7  = C7 + D7; Key8  = C8 + D8
Key9  = C9 + D9; Key10 = C10 + D10; Key11 = C11 + D11; Key12 = C12 + D12
Key13 = C13 + D13; Key14 = C14 + D14; Key15 = C15 + D15; Key16 = C16 + D16


In [ ]:
PC2 = [14,    17,   11,    24,     1,    5,
        3,     28,   15,     6,    21,   10,
        23,    19,   12,     4,    26,    8,
        16,     7,   27,    20,    13,    2,
        41,    52,   31,    37,    47,   55,
        30,    40,   51,    45,    33,   48,
        44,    49,   39,    56,    34,   53,
        46,    42,   50,    36,    29,   32]

In [ ]:
tempPCList1  = []; tempPCList2  = []; tempPCList3  = []; tempPCList4  = [];
tempPCList5  = []; tempPCList6  = []; tempPCList7  = []; tempPCList8  = [];
tempPCList9  = []; tempPCList10 = []; tempPCList11 = []; tempPCList12 = [];
tempPCList13 = []; tempPCList14 = []; tempPCList15 = []; tempPCList16 = [];


s = ""
i = 0

while (i <= len(PC2) - 1):

  tempPCList1.append(Key1[PC2[i] - 1]); tempPCList2.append(Key2[PC2[i] - 1])
  tempPCList3.append(Key3[PC2[i] - 1]); tempPCList4.append(Key4[PC2[i] - 1])
  tempPCList5.append(Key5[PC2[i] - 1]); tempPCList6.append(Key6[PC2[i] - 1])
  tempPCList7.append(Key7[PC2[i] - 1]); tempPCList8.append(Key8[PC2[i] - 1])
  tempPCList9.append(Key9[PC2[i] - 1]); tempPCList10.append(Key10[PC2[i] - 1])
  tempPCList11.append(Key11[PC2[i] - 1]); tempPCList12.append(Key12[PC2[i] - 1])
  tempPCList13.append(Key13[PC2[i] - 1]); tempPCList14.append(Key14[PC2[i] - 1])
  tempPCList15.append(Key15[PC2[i] - 1]); tempPCList16.append(Key16[PC2[i] - 1])

  i += 1

print("The 16 sub keys for the encryption operartion are: \n")

K1 = s.join(tempPCList1); K2 = s.join(tempPCList2)
K3 = s.join(tempPCList3); K4 = s.join(tempPCList4)
K5 = s.join(tempPCList5); K6 = s.join(tempPCList6)
K7 = s.join(tempPCList7); K8 = s.join(tempPCList8)
K9 = s.join(tempPCList9); K10 = s.join(tempPCList10)
K11 = s.join(tempPCList11); K12 = s.join(tempPCList12)
K13 = s.join(tempPCList13); K14 = s.join(tempPCList14)
K15 = s.join(tempPCList15); K16 = s.join(tempPCList16)

List_of_Keys = [K1, K2, K3, K4, K5, K6, K7, K8, K9, K10, K11, K12, K13, K14, K15, K16 ]

print("K1  =",K1); print("K2  =" ,K2); print("K3  =" ,K3); print("K4  =" ,K4)
print("K5  =" ,K5); print("K6  =" ,K6); print("K7  =" ,K7); print("K8  =" ,K8)
print("K9  =" ,K9); print("K10 =" ,K10); print("K11 =" ,K11); print("K12 =" ,K12)
print("K13 =" ,K13); print("K14 =" ,K14); print("K15 =" ,K15); print("K16 =" ,K16)

The 16 sub keys for the encryption operartion are: 

K1  = 111000001011111001100110011010111100000001110010
K2  = 111000001011011001110110110100101100101111101010
K3  = 111001001101011001110110000101001001111100011001
K4  = 111001101101001101110010110110110011010001110000
K5  = 101011101101001101110011011010011110101100101000
K6  = 101011110101001101011011001100000111110000011110
K7  = 001011110101001111011001111011010001000010110110
K8  = 000111110101100111011001100001010110101011101011
K9  = 000111110100100111011001011100010110111100000001
K10 = 000111110110100110011101111110100000000000011110
K11 = 000111110010110110001101110001010111001110001110
K12 = 010110110010110010101101001101000011001011101001
K13 = 110110011010110010101100111100101001100001100111
K14 = 110100001010111010101110000001101010111110111010
K15 = 111100001011111000100110001111010011110101010001
K16 = 111100001011111000100110111011100001001001100101


Proses encipher

### matriks

In [ ]:
E = [32,     1,    2,     3,     4,    5,
      4,     5,    6,     7,     8,    9,
      8,     9,   10,    11,    12,   13,
     12,    13,   14,    15,    16,   17,
     16,    17,   18,    19,    20,   21,
     20,    21,   22,    23,    24,   25,
     24,    25,   26,    27,    28,   29,
     28,    29,   30,    31,    32,    1]

Sboxes = [

        {'000000':'1110', '000010':'0100', '000100':'1101', '000110':'0001', '001000':'0010', '001010':'1111', '001100':'1011', '001110':'1000',
         '010000':'0011', '010010':'1010', '010100':'0110', '010110':'1100', '011000':'0101', '011010':'1001', '011100':'0000', '011110':'0111',
         '000001':'0000', '000011':'1111', '000101':'0111', '000111':'0100', '001001':'1110', '001011':'0010', '001101':'1101', '001111':'0001',
         '010001':'1010', '010011':'0110', '010101':'1100', '010111':'1011', '011001':'1001', '011011':'0101', '011101':'0011', '011111':'1000',
         '100000':'0100', '100010':'0001', '100100':'1110', '100110':'1000', '101000':'1101', '101010':'0110', '101100':'0010', '101110':'1011',
         '110000':'1111', '110010':'1100', '110100':'1001', '110110':'0111', '111000':'0011', '111010':'1010', '111100':'0101', '111110':'0000',
         '100001':'1111', '100011':'1100', '100101':'1000', '100111':'0010', '101001':'0100', '101011':'1001', '101101':'0001', '101111':'0111',
         '110001':'0101', '110011':'1011', '110101':'0011', '110111':'1110', '111001':'1010', '111011':'0000', '111101':'0110', '111111':'1101'},

        {'000000':'1111', '000010':'0001', '000100':'1000', '000110':'1110', '001000':'0110', '001010':'1011', '001100':'0011', '001110':'0100',
         '010000':'1001', '010010':'0111', '010100':'0010', '010110':'1101', '011000':'1100', '011010':'0000', '011100':'0101', '011110':'1010',
         '000001':'0011', '000011':'1101', '000101':'0100', '000111':'0111', '001001':'1111', '001011':'0010', '001101':'1000', '001111':'1110',
         '010001':'1100', '010011':'0000', '010101':'0001', '010111':'1010', '011001':'0110', '011011':'1001', '011101':'1011', '011111':'0101',
         '100000':'0000', '100010':'1110', '100100':'0111', '100110':'1011', '101000':'1010', '101010':'0100', '101100':'1101', '101110':'0001',
         '110000':'0101', '110010':'1000', '110100':'1100', '110110':'0110', '111000':'1001', '111010':'0011', '111100':'0010', '111110':'1111',
         '100001':'1101', '100011':'1000', '100101':'1010', '100111':'0001', '101001':'0011', '101011':'1111', '101101':'0100', '101111':'0010',
         '110001':'1011', '110011':'0110', '110101':'0111', '110111':'1100', '111001':'0000', '111011':'0101', '111101':'1110', '111111':'1001'},

        {'000000':'1010', '000010':'0000', '000100':'1001', '000110':'1110', '001000':'0110', '001010':'0011', '001100':'1111', '001110':'0101',
         '010000':'0001', '010010':'1101', '010100':'1100', '010110':'0111', '011000':'1011', '011010':'0100', '011100':'0010', '011110':'1000',
         '000001':'1011', '000011':'0111', '000101':'0000', '000111':'1001', '001001':'0011', '001011':'0100', '001101':'0110', '001111':'1010',
         '010001':'0010', '010011':'1000', '010101':'0101', '010111':'1110', '011001':'1100', '011011':'1011', '011101':'1111', '011111':'0001',
         '100000':'1101', '100010':'0110', '100100':'0100', '100110':'1001', '101000':'1000', '101010':'1111', '101100':'0011', '101110':'0000',
         '110000':'1011', '110010':'0001', '110100':'0010', '110110':'1100', '111000':'0101', '111010':'1010', '111100':'1110', '111110':'0111',
         '100001':'0001', '100011':'1010', '100101':'1011', '100111':'0000', '101001':'0110', '101011':'1001', '101101':'1000', '101111':'0111',
         '110001':'0100', '110011':'1111', '110101':'1110', '110111':'0011', '111001':'1011', '111011':'0101', '111101':'0010', '111111':'1100'},

        {'000000':'0111', '000010':'1101', '000100':'1110', '000110':'0011', '001000':'0000', '001010':'0110', '001100':'1001', '001110':'1010',
         '010000':'0001', '010010':'0010', '010100':'1000', '010110':'0101', '011000':'1011', '011010':'1100', '011100':'0100', '011110':'1111',
         '000001':'1101', '000011':'1000', '000101':'1101', '000111':'0101', '001001':'0110', '001011':'1111', '001101':'0000', '001111':'0011',
         '010001':'0100', '010011':'0111', '010101':'0010', '010111':'1100', '011001':'0001', '011011':'1010', '011101':'1110', '011111':'1001',
         '100000':'1010', '100010':'0110', '100100':'1001', '100110':'0000', '101000':'1100', '101010':'1011', '101100':'0111', '101110':'1101',
         '110000':'1111', '110010':'0001', '110100':'0011', '110110':'1101', '111000':'0101', '111010':'0010', '111100':'1000', '111110':'0100',
         '100001':'0011', '100011':'1111', '100101':'0000', '100111':'0110', '101001':'1010', '101011':'0001', '101101':'1101', '101111':'1000',
         '110001':'1001', '110011':'0100', '110101':'0101', '110111':'1011', '111001':'1100', '111011':'0111', '111101':'0010', '111111':'1110'},

        {'000000':'0010', '000010':'1100', '000100':'0100', '000110':'0001', '001000':'0111', '001010':'1010', '001100':'1011', '001110':'0110',
         '010000':'1000', '010010':'0101', '010100':'0011', '010110':'1111', '011000':'1101', '011010':'0000', '011100':'1110', '011110':'1001',
         '000001':'1110', '000011':'1011', '000101':'0010', '000111':'1100', '001001':'0100', '001011':'0111', '001101':'1101', '001111':'0001',
         '010001':'0101', '010011':'0000', '010101':'1111', '010111':'1010', '011001':'0011', '011011':'1001', '011101':'1000', '011111':'0110',
         '100000':'0100', '100010':'0010', '100100':'0001', '100110':'1011', '101000':'1010', '101010':'1101', '101100':'0111', '101110':'1000',
         '110000':'1111', '110010':'1001', '110100':'1100', '110110':'0101', '111000':'0110', '111010':'0011', '111100':'0000', '111110':'0100',
         '100001':'1011', '100011':'1000', '100101':'1100', '100111':'0111', '101001':'0001', '101011':'1110', '101101':'0010', '101111':'1101',
         '110001':'0110', '110011':'1111', '110101':'0000', '110111':'1001', '111001':'1010', '111011':'0100', '111101':'0101', '111111':'0011'},

        {'000000':'1100', '000010':'0001', '000100':'1010', '000110':'1111', '001000':'1001', '001010':'0010', '001100':'0110', '001110':'1000',
         '010000':'0000', '010010':'1101', '010100':'0011', '010110':'0100', '011000':'1110', '011010':'0111', '011100':'0101', '011110':'1011',
         '000001':'1010', '000011':'1111', '000101':'0100', '000111':'0010', '001001':'0111', '001011':'1100', '001101':'1001', '001111':'0101',
         '010001':'0110', '010011':'0001', '010101':'1101', '010111':'1110', '011001':'0000', '011011':'1011', '011101':'0011', '011111':'1000',
         '100000':'1001', '100010':'1110', '100100':'1111', '100110':'0101', '101000':'0010', '101010':'1000', '101100':'1100', '101110':'0011',
         '110000':'0111', '110010':'0000', '110100':'0100', '110110':'1010', '111000':'0001', '111010':'1101', '111100':'1011', '111110':'0110',
         '100001':'0100', '100011':'0011', '100101':'0010', '100111':'1100', '101001':'1001', '101011':'0101', '101101':'1111', '101111':'1010',
         '110001':'1011', '110011':'1110', '110101':'0001', '110111':'0111', '111001':'0110', '111011':'0000', '111101':'1000', '111111':'1101'},

        {'000000':'0100', '000010':'1011', '000100':'0010', '000110':'1110', '001000':'1111', '001010':'0000', '001100':'1000', '001110':'1101',
         '010000':'0011', '010010':'1100', '010100':'1001', '010110':'0111', '011000':'0101', '011010':'1010', '011100':'0110', '011110':'0001',
         '000001':'1101', '000011':'0000', '000101':'1011', '000111':'0111', '001001':'0100', '001011':'1001', '001101':'0001', '001111':'1010',
         '010001':'1110', '010011':'0011', '010101':'0101', '010111':'1100', '011001':'0010', '011011':'1111', '011101':'1000', '011111':'0110',
         '100000':'0001', '100010':'0100', '100100':'1011', '100110':'1101', '101000':'1100', '101010':'0011', '101100':'0111', '101110':'1110',
         '110000':'1010', '110010':'1111', '110100':'0110', '110110':'1000', '111000':'0000', '111010':'0101', '111100':'1001', '111110':'0010',
         '100001':'0110', '100011':'1011', '100101':'1101', '100111':'1000', '101001':'0001', '101011':'0100', '101101':'1010', '101111':'0111',
         '110001':'1001', '110011':'0101', '110101':'0000', '110111':'1111', '111001':'1110', '111011':'0010', '111101':'0011', '111111':'1100'},

        {'000000':'1101', '000010':'0010', '000100':'1000', '000110':'0100', '001000':'0110', '001010':'1111', '001100':'1011', '001110':'0001',
         '010000':'1010', '010010':'1001', '010100':'0011', '010110':'1110', '011000':'0101', '011010':'0000', '011100':'1100', '011110':'0111',
         '000001':'0001', '000011':'1111', '000101':'1101', '000111':'1000', '001001':'1010', '001011':'0011', '001101':'0111', '001111':'0100',
         '010001':'1100', '010011':'0101', '010101':'0110', '010111':'1011', '011001':'0000', '011011':'1110', '011101':'1001', '011111':'0010',
         '100000':'0111', '100010':'1011', '100100':'0100', '100110':'0001', '101000':'1001', '101010':'1100', '101100':'1110', '101110':'0010',
         '110000':'0000', '110010':'0110', '110100':'1010', '110110':'1101', '111000':'1111', '111010':'0011', '111100':'0101', '111110':'1000',
         '100001':'0010', '100011':'0001', '100101':'1110', '100111':'0111', '101001':'0100', '101011':'1010', '101101':'1000', '101111':'1101',
         '110001':'1111', '110011':'1100', '110101':'1001', '110111':'0000', '111001':'0011', '111011':'0101', '111101':'0110', '111111':'1011'},

        ]

PBox = [16,   7,  20,  21, 29,  12,  28,  17,
         1,  15,  23,  26, 5,  18,  31,  10,
         2,   8,  24,  14, 32,  27,   3,   9,
        19,  13,  30,   6, 22,  11,   4,  25]

ipInverse = [ 40,     8,   48,    16,    56,   24,    64,   32,
              39,     7,   47,    15,    55,   23,    63,   31,
              38,     6,   46,    14,    54,   22,    62,   30,
              37,     5,   45,    13,    53,   21,    61,   29,
              36,     4,   44,    12,    52,   20,    60,   28,
              35,     3,   43,    11,    51,   19,    59,   27,
              34,     2,   42,    10,    50,   18,    58,   26,
              33,     1,   41,     9,    49,   17,    57,   25]

## jaringan feistel

In [ ]:
L0 = msgIP[:32]
R0 = msgIP[-32:]

LeftSideList = [L0]
RightSideList = [R0]

print(LeftSideList[0], " ", RightSideList[0],"\n")
for i in range(16):
    print("Encryption:"," ","Round", i+1)
    LeftSideList.append(RightSideList[i])

    # 32 bit
    tempERList = []
    s = ""
    m = 0
    R = RightSideList[i]


    # fungsi f
    while (m <= len(E) - 1):
      tempERList.append(R[E[m] - 1])
      m += 1

    # 48 bit
    ER = s.join(tempERList)


    tempF = []
    s = ""
    SUB_KEY= List_of_Keys[i]

    for x in range(48):
      if (SUB_KEY[x] == '0' and ER[x] == '0' or SUB_KEY[x] == '1' and ER[x] == '1'):
          tempF.append('0')
      elif (SUB_KEY[x] == '0' and ER[x] == '1' or SUB_KEY[x] == '1' and ER[x] == '0'):
          tempF.append('1')

    xorV = s.join(tempF)


    # per 6 bit
    divideR = []
    start = 0; inc = 5; end = 47
    while(start <= end):
      divideR.append(xorV[start:inc + 1])
      start = inc + 1
      inc += 6



    tempSboxesList = []
    for p in range(len(divideR)):
        item = divideR[p]
        dict = Sboxes[p]
        tempSboxesList.append(dict[item])
    # 32 bit
    Results_of_Sboxes = s.join(tempSboxesList)



    # P-Box permutation
    counter = 0
    s = ''
    tempFList = []
    while (counter <= len(PBox) - 1):
       tempFList.append(Results_of_Sboxes[PBox[counter] - 1])
       counter += 1

    F = s.join(tempFList)


    # 32 bit
    tempNewR = []
    s = ''
    PreviousL = LeftSideList[i]
    for n in range(32):
      if (F[n] == '0' and PreviousL[n] == '0' or F[n] == '1' and PreviousL[n] == '1'):
          tempNewR.append('0')
      elif (F[n] == '0' and PreviousL[n] == '1' or F[n] == '1' and PreviousL[n] == '0'):
          tempNewR.append('1')
    NextR = s.join(tempNewR)
    RightSideList.append(NextR)

    print("R lanjut : ",NextR,"\n")

    print(LeftSideList[i+1], " ", RightSideList[i+1],"\n")






11111111000001001011001011101010   00000000111111111101000111110101 

Encryption:   Round 1
R lanjut :  00101011000110000111101111001001 

00000000111111111101000111110101   00101011000110000111101111001001 

Encryption:   Round 2
R lanjut :  11011010100000011011111011010011 

00101011000110000111101111001001   11011010100000011011111011010011 

Encryption:   Round 3
R lanjut :  10000100000000001010101111000100 

11011010100000011011111011010011   10000100000000001010101111000100 

Encryption:   Round 4
R lanjut :  10001001101010100000011011011111 

10000100000000001010101111000100   10001001101010100000011011011111 

Encryption:   Round 5
R lanjut :  11001010110110111101011111010111 

10001001101010100000011011011111   11001010110110111101011111010111 

Encryption:   Round 6
R lanjut :  00100101010011010001110011111011 

11001010110110111101011111010111   00100101010011010001110011111011 

Encryption:   Round 7
R lanjut :  11100111111101110001110010110100 

001001010100110100011100111

In [ ]:
for i in range(16):
 if (i == 15):

    tempCipher = RightSideList[i + 1] + LeftSideList[i + 1]

    count = 0
    s = ''
    tempCipherList = []
    while (count <= len(ipInverse) - 1):
          tempCipherList.append(tempCipher[ipInverse[count] - 1])
          count += 1

    Cipher = s.join(tempCipherList)

    divideCipher = []; start = 0; inc = 3; end = 63
    while(start <= end):
        divideCipher.append(Cipher[start:inc + 1])
        start = inc + 1
        inc += 4

    #print(divideCipher)
    Cipher_Hexa_List = []
    s = ''
    for c1 in divideCipher:
          for d1 in hexa_to_bin:
                if c1 == hexa_to_bin[d1]:
                    Cipher_Hexa_List.append(d1)
    #print(Cipher_Hexa)
    Cipher_Hexa = s.join(Cipher_Hexa_List)


In [ ]:
print("Cipher biner text ="," ",Cipher)
print("Cipher Hexa text ="," ",Cipher_Hexa)

Cipher biner text =   1011001110000001101111101110111010101111101110011111110100011101
Cipher Hexa text =   b381beeeafb9fd1d


# Dekripsi

In [ ]:
tempIPList = []
s = ""
i = 0

while (i <= len(IP) - 1):
   tempIPList.append(Cipher[IP[i] - 1])
   i += 1

print("The message after the IP")
msgIP = s.join(tempIPList)
print(msgIP, "\n")

The message after the IP
0100100011100101110111001111001101111111011111011111110000011101 



In [ ]:
R16 = msgIP[:32]
L16 = msgIP[-32:]
# 32 bit
LeftSideList = [R16]
RightSideList = [L16]

In [ ]:
i = 0
s = ""

permuted_key = [binKey[i - 1] for i in PC1]

#print("The message after the IP \n")
# 56 bit
keyPC1 = s.join(permuted_key)
print(keyPC1, "\n")

#Langkah 5
# 28 bit
C0 = keyPC1[:28]
D0 = keyPC1[-28:]

LeftSideKey = [C0]
#C0
formatted_binary_C0 = ' '.join([C0[i:i+7] for i in range(0, len(C0), 7)])
print("C0 : "+formatted_binary_C0)

RightSideKey = [D0]
#D0
formatted_binary_D0 = ' '.join([D0[i:i+7] for i in range(0, len(D0), 7)])
print("D0 : "+formatted_binary_D0)

00000000111111111111111100000111000100101010011100011110 

C0 : 0000000 0111111 1111111 1110000
D0 : 0111000 1001010 1001110 0011110


In [ ]:
R16 = msgIP[:32]
L16 = msgIP[-32:]

LeftSideList = [R16]
RightSideList = [L16]

print(LeftSideList[0], " ", RightSideList[0],"\n")
for i in range(16):
  print("Decryption:"," ","Round", i + 1)
  LeftSideList.append(RightSideList[i])
  # 32 bit
  # fungsi f
  tempERList = []
  s = ""
  m = 0
  R = RightSideList[i]
  while (m <= len(E) - 1):
      tempERList.append(R[E[m] - 1])
      m += 1
  # 48 bit
  ER = s.join(tempERList)

  tempF = []
  s = ""
  SUB_KEY= List_of_Keys[15 - i]

  for x in range(48):
     if (SUB_KEY[x] == '0' and ER[x] == '0' or SUB_KEY[x] == '1' and ER[x] == '1'):
              tempF.append('0')
     elif (SUB_KEY[x] == '0' and ER[x] == '1' or SUB_KEY[x] == '1' and ER[x] == '0'):
              tempF.append('1')

  xorV = s.join(tempF)
  # per 6 bit
  divideR = []; start = 0; inc = 5; end = 47
  while(start <= end):
          divideR.append(xorV[start:inc + 1])
          start = inc + 1
          inc += 6


  tempSboxesList = []
  for p in range(len(divideR)):
    item = divideR[p]
    dict = Sboxes[p]
    tempSboxesList.append(dict[item])
  # 32 bit
  Results_of_Sboxes = s.join(tempSboxesList)

  # P-Box permutation
  counter = 0
  s = ''
  tempFList = []
  while (counter <= len(PBox) - 1):
       tempFList.append(Results_of_Sboxes[PBox[counter] - 1])
       counter += 1
  F = s.join(tempFList)

  # 32 bit
  tempNewR = []
  s = ''
  PreviousR = LeftSideList[i]
  for n in range(32):
       if (F[n] == '0' and PreviousR[n] == '0' or F[n] == '1' and PreviousR[n] == '1'):
              tempNewR.append('0')
       elif (F[n] == '0' and PreviousR[n] == '1' or F[n] == '1' and PreviousR[n] == '0'):
              tempNewR.append('1')


  NextL = s.join(tempNewR)
  RightSideList.append(NextL)

  print(NextL,"\n")
  print(LeftSideList[i + 1], " ", RightSideList[i+1],"\n")

01001000111001011101110011110011   01111111011111011111110000011101 

Decryption:   Round 1
00001000101000100000111110100111 

01111111011111011111110000011101   00001000101000100000111110100111 

Decryption:   Round 2
01111001000010111110111010010010 

00001000101000100000111110100111   01111001000010111110111010010010 

Decryption:   Round 3
00001110100110000111001011001011 

01111001000010111110111010010010   00001110100110000111001011001011 

Decryption:   Round 4
00010100101010011011010010101000 

00001110100110000111001011001011   00010100101010011011010010101000 

Decryption:   Round 5
00011100100101101010100011001011 

00010100101010011011010010101000   00011100100101101010100011001011 

Decryption:   Round 6
01100100010110000001111011000001 

00011100100101101010100011001011   01100100010110000001111011000001 

Decryption:   Round 7
11110110001010101101100110111001 

01100100010110000001111011000001   11110110001010101101100110111001 

Decryption:   Round 8
1110011111110111000

In [ ]:
if (i == 15):
    tempPlain = RightSideList[i + 1] + LeftSideList[i + 1]

    count = 0
    s = ''
    tempPlainList = []
    while (count <= len(ipInverse) - 1):
          tempPlainList.append(tempPlain[ipInverse[count] - 1])
          count += 1

    plain = s.join(tempPlainList)
    print("Plain text ="," ",plain)

Plain text =   0110101001100101011100100110000101101110011001110110101101101111


In [ ]:
dividePlaintxt = []; start = 0; inc = 3; end = 63
while(start <= end):
  dividePlaintxt.append(plain[start:inc + 1])
  start = inc + 1
  inc += 4

#print(divideCipher)
Plain_Hexa_List = []
s = ''
for c1 in dividePlaintxt:
    for d1 in hexa_to_bin:
        if c1 == hexa_to_bin[d1]:
            Plain_Hexa_List.append(d1)

#print(Cipher_Hexa)
Plain_Hexa = s.join(Plain_Hexa_List)
dividePlainHexa = []; start = 0; inc = 1; end = 15
while(start <= end):
    dividePlainHexa.append(Plain_Hexa[start:inc + 1])
    start = inc + 1
    inc += 2
print(dividePlainHexa)

Plain_Char_List = []
s = ''
for h1 in dividePlainHexa:
    for c1 in hexa_to_char:
      if h1 == c1:
         Plain_Char_List.append(hexa_to_char[c1])


finalPlain_Text = s.join(Plain_Char_List)
print(finalPlain_Text)

['6a', '65', '72', '61', '6e', '67', '6b', '6f']
jerangko
